<?php

namespace App\Services;

class LanguageService
{
    public function getLanguages()
    {
        return [
            "af" => "Afrikaans",
            "sq" => "Albanian",
            "am" => "Amharic",
            "ar" => "Arabic",
            "an" => "Aragonese",
            "hy" => "Armenian",
            "ast" => "Asturian",
            "az" => "Azerbaijani",
            "eu" => "Basque",
            "be" => "Belarusian",
            "bn" => "Bengali",
            "bs" => "Bosnian",
            "br" => "Breton",
            "bg" => "Bulgarian",
            "ca" => "Catalan",
            "ckb" => "Central Kurdish",
            "zh" => "Chinese",
            "zh-HK" => "Chinese (Hong Kong)",
            "zh-CN" => "Chinese (Simplified)",
            "zh-TW" => "Chinese (Traditional)",
            "co" => "Corsican",
            "hr" => "Croatian",
            "cs" => "Czech",
            "da" => "Danish",
            "nl" => "Dutch",
            "en" => "English",
            "en-AU" => "English (Australia)",
            "en-CA" => "English (Canada)",
            "en-IN" => "English (India)",
            "en-NZ" => "English (New Zealand)",
            "en-ZA" => "English (South Africa)",
            "en-UK" => "English (United Kingdom)",
            "en-US" => "English (United States)",
            "eo" => "Esperanto",
            "et" => "Estonian",
            "fo" => "Faroese",
            "fil" => "Filipino",
            "fi" => "Finnish",
            "fr" => "French",
            "gl" => "Galician",
            "ka" => "Georgian",
            "de" => "German",
            "el" => "Greek",
            "gn" => "Guarani",
            "gu" => "Gujarati",
            "ha" => "Hausa",
            "haw" => "Hawaiian",
            "he" => "Hebrew",
            "hi" => "Hindi",
            "hu" => "Hungarian",
            "is" => "Icelandic",
            "id" => "Indonesian",
            "ia" => "Interlingua",
            "ga" => "Irish",
            "it" => "Italian",
            "ja" => "Japanese",
            "kn" => "Kannada",
            "kk" => "Kazakh",
            "km" => "Khmer",
            "ko" => "Korean",
            "ku" => "Kurdish",
            "ky" => "Kyrgyz",
            "lo" => "Lao",
            "la" => "Latin",
            "lv" => "Latvian",
            "ln" => "Lingala",
            "lt" => "Lithuanian",
            "mk" => "Macedonian",
            "ms" => "Malay",
            "ml" => "Malayalam",
            "mt" => "Maltese",
            "mr" => "Marathi",
            "mn" => "Mongolian",
            "ne" => "Nepali",
            "no" => "Norwegian",
            "nb" => "Norwegian Bokmål",
            "nn" => "Norwegian Nynorsk",
            "oc" => "Occitan",
            "or" => "Oriya",
            "om" => "Oromo",
            "ps" => "Pashto",
            "fa" => "Persian",
            "pl" => "Polish",
            "pt" => "Portuguese",
            "pa" => "Punjabi",
            "qu" => "Quechua",
            "ro" => "Romanian",
            "mo" => "Romanian (Moldova)",
            "rm" => "Romansh",
            "ru" => "Russian",
            "gd" => "Scottish Gaelic",
            "sr" => "Serbian",
            "sh" => "Serbo-Croatian",
            "sn" => "Shona",
            "sd" => "Sindhi",
            "si" => "Sinhala",
            "sk" => "Slovak",
            "sl" => "Slovenian",
            "so" => "Somali",
            "st" => "Southern Sotho",
            "es" => "Spanish",
            "su" => "Sundanese",
            "sw" => "Swahili",
            "sv" => "Swedish",
            "tg" => "Tajik",
            "ta" => "Tamil",
            "tt" => "Tatar",
            "te" => "Telugu",
            "th" => "Thai",
            "ti" => "Tigrinya",
            "to" => "Tongan",
            "tr" => "Turkish",
            "tk" => "Turkmen",
            "tw" => "Twi",
            "uk" => "Ukrainian",
            "ur" => "Urdu",
            "ug" => "Uyghur",
            "uz" => "Uzbek",
            "vi" => "Vietnamese",
            "wa" => "Walloon",
            "cy" => "Welsh",
            "fy" => "Western Frisian",
            "xh" => "Xhosa",
            "yi" => "Yiddish",
            "yo" => "Yoruba",
            "zu" => "Zulu"
        ];

    }

}
